---
abstract: 'Math with big numbers in pure perl with no deps'
author:
  - 'Ralf Peine, C<< <ralf.peine at jupiter-program.de> >>'
  - 'Ralf Peine <ralf.peine@jupiter-program.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-GoldenBigMath
no_index:
  directory:
    - inc
    - t
    - xt
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
